"""Final bug fixes

Revision ID: 21f477cb722c
Revises: 6c777dfc073b
Create Date: 2025-08-28 22:28:40.858517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f477cb722c'
down_revision = '6c777dfc073b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('bukti_pembayaran')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bukti_pembayaran', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
