"""Tambah tanggal bergabung dan buat package_id opsional

Revision ID: 25831971353f
Revises: 9d85ed562ccc
Create Date: 2025-08-14 17:27:38.377645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25831971353f'
down_revision = '9d85ed562ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
