"""Inisialisasi sistem migrasi

Revision ID: 677c8a728df6
Revises: 
Create Date: 2025-08-14 17:01:13.921098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677c8a728df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.String(length=200), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_paket', sa.String(length=100), nullable=False),
    sa.Column('kecepatan', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=200), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tanggal_bergabung', sa.DateTime(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['service_package.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telepon')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tanggal_buat', sa.DateTime(), nullable=False),
    sa.Column('tanggal_lunas', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('customer')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('service_package')
    op.drop_table('expense')
    # ### end Alembic commands ###
