"""Perpanjang kolom bukti_pembayaran

Revision ID: 6c777dfc073b
Revises: 25831971353f
Create Date: 2025-08-19 02:25:59.267308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c777dfc073b'
down_revision = '25831971353f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bukti_pembayaran', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('bukti_pembayaran')

    # ### end Alembic commands ###
