"""Tambah tanggal bergabung untuk pelanggan

Revision ID: 9d85ed562ccc
Revises: 677c8a728df6
Create Date: 2025-08-14 17:18:57.475832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d85ed562ccc'
down_revision = '677c8a728df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('catatan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
