"""Tambah kembali kolom bukti_pembayaran ke Invoice

Revision ID: adbec801a4e9
Revises: 21f477cb722c
Create Date: 2025-08-28 22:55:20.548779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbec801a4e9'
down_revision = '21f477cb722c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bukti_pembayaran', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('bukti_pembayaran')

    # ### end Alembic commands ###
